# stocks.py — All symbols verified against Yahoo Finance (.NS format)
# F&O list sourced from NSE via Dhan (March 2026) — 211 stocks

SECTORS = {
    "PHARMA": [
        "SUNPHARMA.NS", "DRREDDY.NS", "DIVISLAB.NS", "CIPLA.NS",
        "TORNTPHARM.NS", "AUROPHARMA.NS", "LUPIN.NS", "ALKEM.NS",
        "BIOCON.NS", "LAURUSLABS.NS", "MANKIND.NS", "ZYDUSLIFE.NS",
        "GLENMARK.NS", "IPCALAB.NS", "SYNGENE.NS", "MAXHEALTH.NS",
        "FORTIS.NS", "APOLLOHOSP.NS", "PPLPHARMA.NS",
    ],

    "AUTO": [
        "MARUTI.NS", "M&M.NS", "BAJAJ-AUTO.NS",
        "EICHERMOT.NS", "HEROMOTOCO.NS", "TVSMOTOR.NS", "ASHOKLEY.NS",
        "UNOMINDA.NS", "MOTHERSON.NS", "TIINDIA.NS", "BOSCHLTD.NS",
        "BHARATFORG.NS", "APOLLOTYRE.NS", "MRF.NS", "BALKRISIND.NS",
        "SONACOMS.NS", "EXIDEIND.NS", "TRENT.NS", "TATAMOTORS.NS",
    ],

    "IT": [
        "TCS.NS", "INFY.NS", "WIPRO.NS", "HCLTECH.NS", "TECHM.NS",
        "LTM.NS", "MPHASIS.NS", "PERSISTENT.NS", "OFSS.NS",
        "COFORGE.NS", "LTTS.NS", "TATAELXSI.NS", "KPITTECH.NS",
        "NAUKRI.NS", "POLICYBZR.NS", "PAYTM.NS", "TATATECH.NS",
    ],

    "BANKING & FINANCE": [
        "HDFCBANK.NS", "ICICIBANK.NS", "SBIN.NS", "KOTAKBANK.NS",
        "AXISBANK.NS", "INDUSINDBK.NS", "BANDHANBNK.NS", "FEDERALBNK.NS",
        "IDFCFIRSTB.NS", "RBLBANK.NS", "PNB.NS", "BANKBARODA.NS",
        "CANBK.NS", "UNIONBANK.NS", "YESBANK.NS", "AUBANK.NS",
        "INDIANB.NS", "BANKINDIA.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS",
        "CHOLAFIN.NS", "SHRIRAMFIN.NS", "MUTHOOTFIN.NS", "MANAPPURAM.NS",
        "LTF.NS", "PNBHOUSING.NS", "LICHSGFIN.NS", "RECLTD.NS",
        "PFC.NS", "IREDA.NS", "HUDCO.NS", "HDFCLIFE.NS", "SBILIFE.NS",
        "ICICIGI.NS", "ICICIPRULI.NS", "HDFCAMC.NS", "ANGELONE.NS",
        "CDSL.NS", "BSE.NS", "MCX.NS", "CAMS.NS", "KFINTECH.NS",
        "BAJAJHLDNG.NS", "MFSL.NS", "NUVAMA.NS", "JIOFIN.NS",
        "360ONE.NS", "LICI.NS", "SBICARD.NS", "SAMMAANCAP.NS",
    ],

    "METALS": [
        "TATASTEEL.NS", "JSWSTEEL.NS", "HINDALCO.NS", "VEDL.NS",
        "COALINDIA.NS", "NATIONALUM.NS", "HINDZINC.NS", "SAIL.NS",
        "NMDC.NS", "JINDALSTEL.NS", "JSWENERGY.NS", "APLAPOLLO.NS",
        "WELCORP.NS", "GPIL.NS", "MOIL.NS",
    ],

    "REALTY": [
        "DLF.NS", "GODREJPROP.NS", "LODHA.NS", "PRESTIGE.NS",
        "PHOENIXLTD.NS", "OBEROIRLTY.NS", "SOBHA.NS", "BRIGADE.NS",
        "NBCC.NS", "RVNL.NS", "HUDCO.NS",
    ],

    "ENERGY": [
        "RELIANCE.NS", "ONGC.NS", "NTPC.NS", "POWERGRID.NS",
        "ADANIGREEN.NS", "TATAPOWER.NS", "TORNTPOWER.NS", "BPCL.NS",
        "HINDPETRO.NS", "IOC.NS", "GAIL.NS", "OIL.NS",
        "IGL.NS", "MGL.NS", "PETRONET.NS", "SUZLON.NS",
        "WAAREEENER.NS", "PREMIERENE.NS", "INOXWIND.NS", "IRFC.NS",
        "NHPC.NS", "SOLARINDS.NS", "ADANIENSOL.NS", "IEX.NS",
    ],

    "FMCG": [
        "HINDUNILVR.NS", "ITC.NS", "NESTLEIND.NS", "BRITANNIA.NS",
        "DABUR.NS", "GODREJCP.NS", "COLPAL.NS", "MARICO.NS",
        "TATACONSUM.NS", "VBL.NS", "DMART.NS", "JUBLFOOD.NS",
        "UNITDSPR.NS", "RADICO.NS", "KALYANKJIL.NS", "ETERNAL.NS",
        "SWIGGY.NS", "NYKAA.NS", "PATANJALI.NS",
    ],

    "INFRA & CAPITAL GOODS": [
        "LT.NS", "SIEMENS.NS", "ABB.NS", "BHEL.NS", "THERMAX.NS",
        "CUMMINSIND.NS", "HAVELLS.NS", "POLYCAB.NS", "KEI.NS",
        "GMRAIRPORT.NS", "ADANIENT.NS", "ADANIPORTS.NS", "IRCTC.NS",
        "CONCOR.NS", "BEL.NS", "HAL.NS", "COCHINSHIP.NS",
        "MAZDOCK.NS", "GRSE.NS", "TITAGARH.NS", "BDL.NS",
        "CGPOWER.NS", "POWERINDIA.NS", "INDUSTOWER.NS",
        "DELHIVERY.NS", "INDIGO.NS", "ASTRAL.NS",
    ],

    "CHEMICALS": [
        "SRF.NS", "PIDILITIND.NS", "ATUL.NS",
        "NAVINFLUOR.NS", "CLEAN.NS", "AARTIIND.NS",
        "TATACHEM.NS", "GNFC.NS", "GSFC.NS", "NOCIL.NS",
        "SUDARSCHEM.NS", "FINEORG.NS", "PIIND.NS", "UPL.NS",
    ],

    "MEDIA & ENTERTAINMENT": [
        "ZEEL.NS", "SUNTV.NS", "NETWORK18.NS", "PVRINOX.NS",
        "SAREGAMA.NS", "NAZARA.NS",
    ],

    "TELECOM": [
        "BHARTIARTL.NS", "TATACOMM.NS", "IDEA.NS",
        "INDUSTOWER.NS", "HFCL.NS",
    ],

    "CONSUMER DURABLES": [
        "TITAN.NS", "VOLTAS.NS", "BLUESTARCO.NS", "CROMPTON.NS",
        "HAVELLS.NS", "VGUARD.NS", "AMBER.NS", "DIXON.NS",
        "KAYNES.NS", "PGEL.NS", "WHIRLPOOL.NS", "PAGEIND.NS",
    ],

    "PSU & DEFENCE": [
        "HAL.NS", "BEL.NS", "BHEL.NS", "COCHINSHIP.NS", "MAZDOCK.NS",
        "GRSE.NS", "BDL.NS", "IRFC.NS", "RVNL.NS", "NBCC.NS",
        "RECLTD.NS", "PFC.NS", "IREDA.NS", "NMDC.NS", "SAIL.NS",
        "NATIONALUM.NS", "OIL.NS", "HINDPETRO.NS", "BPCL.NS",
        "IOC.NS", "GAIL.NS", "NHPC.NS", "NTPC.NS", "POWERGRID.NS",
    ],

    "NIFTY 50": [
        "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
        "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
        "LT.NS", "AXISBANK.NS", "BAJFINANCE.NS", "ASIANPAINT.NS", "MARUTI.NS",
        "TITAN.NS", "NESTLEIND.NS", "WIPRO.NS", "ULTRACEMCO.NS", "SUNPHARMA.NS",
        "HCLTECH.NS", "POWERGRID.NS", "NTPC.NS", "ONGC.NS", "M&M.NS",
        "INDUSINDBK.NS", "BAJAJFINSV.NS", "COALINDIA.NS", "DRREDDY.NS",
        "DIVISLAB.NS", "CIPLA.NS", "TECHM.NS", "ADANIENT.NS",
        "ADANIPORTS.NS", "TATASTEEL.NS", "HINDALCO.NS", "BPCL.NS",
        "GRASIM.NS", "JSWSTEEL.NS", "APOLLOHOSP.NS", "EICHERMOT.NS",
        "BRITANNIA.NS", "HEROMOTOCO.NS", "TVSMOTOR.NS", "SHREECEM.NS",
        "TATACONSUM.NS", "VEDL.NS", "UPL.NS", "LTM.NS",
    ],

    "NIFTY MIDCAP SELECT": [
        "PERSISTENT.NS", "GODREJPROP.NS", "LODHA.NS", "UNOMINDA.NS",
        "MANKIND.NS", "HDFCAMC.NS", "IRCTC.NS", "COFORGE.NS",
        "SUPREMEIND.NS", "CUMMINSIND.NS", "AUROPHARMA.NS", "FEDERALBNK.NS",
        "IDFCFIRSTB.NS", "ABCAPITAL.NS", "MFSL.NS", "LTTS.NS",
        "KPITTECH.NS", "OBEROIRLTY.NS", "VOLTAS.NS", "DIXON.NS",
        "MPHASIS.NS", "TIINDIA.NS", "CHOLAFIN.NS", "LUPIN.NS",
        "TORNTPHARM.NS", "DALBHARAT.NS", "AMBUJACEM.NS", "INDHOTEL.NS",
    ],
}

# Complete F&O stocks set — verified from NSE (March 2026), 211 stocks
FO_STOCKS = {
    "360ONE", "ABB", "ABCAPITAL", "ADANIENSOL", "ADANIENT", "ADANIGREEN",
    "ADANIPORTS", "ALKEM", "AMBER", "AMBUJACEM", "ANGELONE", "APLAPOLLO",
    "APOLLOHOSP", "ASHOKLEY", "ASIANPAINT", "ASTRAL", "AUBANK", "AUROPHARMA",
    "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV", "BAJAJHLDNG", "BAJFINANCE",
    "BALKRISIND", "BANDHANBNK", "BANKBARODA", "BANKINDIA", "BDL", "BEL",
    "BHARATFORG", "BHARTIARTL", "BHEL", "BIOCON", "BLUESTARCO", "BOSCHLTD",
    "BPCL", "BRITANNIA", "BSE", "CAMS", "CANBK", "CDSL", "CGPOWER",
    "CHOLAFIN", "CIPLA", "COALINDIA", "COFORGE", "COLPAL", "CONCOR",
    "CROMPTON", "CUMMINSIND", "DABUR", "DALBHARAT", "DELHIVERY", "DIVISLAB",
    "DIXON", "DLF", "DMART", "DRREDDY", "EICHERMOT", "ETERNAL", "EXIDEIND",
    "FEDERALBNK", "FORTIS", "GAIL", "GLENMARK", "GMRAIRPORT", "GODREJCP",
    "GODREJPROP", "GRASIM", "HAL", "HAVELLS", "HCLTECH", "HDFCAMC",
    "HDFCBANK", "HDFCLIFE", "HEROMOTOCO", "HINDALCO", "HINDPETRO",
    "HINDUNILVR", "HINDZINC", "HUDCO", "ICICIBANK", "ICICIGI", "ICICIPRULI",
    "IDEA", "IDFCFIRSTB", "IEX", "INDHOTEL", "INDIANB", "INDIGO",
    "INDUSINDBK", "INDUSTOWER", "INFY", "INOXWIND", "IOC", "IREDA",
    "IRFC", "ITC", "JINDALSTEL", "JIOFIN", "JSWENERGY", "JSWSTEEL",
    "JUBLFOOD", "KALYANKJIL", "KAYNES", "KEI", "KFINTECH", "KOTAKBANK",
    "KPITTECH", "LAURUSLABS", "LICHSGFIN", "LICI", "LODHA", "LT",
    "LTF", "LTM", "LTTS", "LUPIN", "M&M", "MANAPPURAM", "MANKIND",
    "MARICO", "MARUTI", "MAXHEALTH", "MAZDOCK", "MCX", "MFSL",
    "MOTHERSON", "MPHASIS", "MUTHOOTFIN", "NATIONALUM", "NAUKRI",
    "NBCC", "NESTLEIND", "NHPC", "NMDC", "NTPC", "NUVAMA", "NYKAA",
    "OBEROIRLTY", "OFSS", "OIL", "ONGC", "PAGEIND", "PATANJALI",
    "PAYTM", "PERSISTENT", "PETRONET", "PFC", "PGEL", "PHOENIXLTD",
    "PIDILITIND", "PIIND", "PNB", "PNBHOUSING", "POLICYBZR", "POLYCAB",
    "POWERGRID", "POWERINDIA", "PPLPHARMA", "PREMIERENE", "PRESTIGE",
    "RBLBANK", "RECLTD", "RELIANCE", "RVNL", "SAIL", "SAMMAANCAP",
    "SBICARD", "SBILIFE", "SBIN", "SHREECEM", "SHRIRAMFIN", "SIEMENS",
    "SOLARINDS", "SONACOMS", "SRF", "SUNPHARMA", "SUPREMEIND", "SUZLON",
    "SWIGGY", "SYNGENE", "TATACONSUM", "TATAELXSI", "TATAPOWER",
    "TATASTEEL", "TATATECH", "TCS", "TECHM", "TIINDIA", "TITAN",
    "TATAMOTORS", "TORNTPHARM", "TORNTPOWER", "TRENT", "TVSMOTOR", "ULTRACEMCO",
    "UNIONBANK", "UNITDSPR", "UNOMINDA", "UPL", "VBL", "VEDL",
    "VOLTAS", "WAAREEENER", "WIPRO", "YESBANK", "ZYDUSLIFE",
}

# All unique symbols flat list
ALL_SYMBOLS = list({
    sym for symbols in SECTORS.values() for sym in symbols
})
